# Generated by Django 3.2.8 on 2021-10-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
