# Generated by Django 3.2.8 on 2021-10-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashy', '0002_auto_20211027_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
